filter:
    paths: [src/*]
    excluded_paths: [test/*]
checks:
    php:
        code_rating: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_code_coverage: false
    php_loc:
        enabled: true
        excluded_dirs: [test, vendor]
    php_cpd:
        enabled: true
        excluded_dirs: [test, vendor]